### ISSUE TITLE
Can you share the pretrained models?

### ISSUE THREAD

**Issue by huchinlp** [ofirpress/shortformer#2]
Nice work and thanks for your code!
I want to reproduce the results (inference speed & test ppl) in your paper.
It will be much easier if you can provide some pretrained models.

Thanks again!

**Comment by ofirpress** [comment]
Hi! 
I put the shortformer model here (this is the one we train with staged training, PIA and caching) - https://dl.fbaipublicfiles.com/shortformer/wikitext103-shortformer.pt

I'll upload the other models soon.

**Comment by huchinlp** [comment]
Thank you so much!

**Comment by ofirpress** [comment]
No problem! Tell me if you encounter any problems.
