### ISSUE TITLE
Question about the GPU used for speed evaluation in your paper?

### ISSUE THREAD

**Issue by taoleicn** [ofirpress/shortformer#3]
Hi, 
Thank you for releasing this interesting work and the code!

I want to refer to your paper and the reported speed numbers in Table 6. But I want to make sure I use the same or comparable GPU for adding new numbers. Could you tell what GPU type is used to compute the speed numbers?

**Comment by ofirpress** [comment]
Hi!
Thanks for reading our paper!

Throughout the paper we used Volta v100 32gb GPUs. As we mention in the paper, we always run inference on just one GPU. 

If you have any more questions feel free to respond here.

**Comment by taoleicn** [comment]
Thank you @ofirpress !
