### ISSUE TITLE
Can you share the split scripts for TBC dataset?

### ISSUE THREAD

**Issue by richardbaihe** [ofirpress/shortformer#4]
I know TBC is not public available but could you share your split scripts for the dataset? I want to compare with your results but don't know how did you split the dataset. Thanks in advance!

**Comment by ofirpress** [comment]
Hi!
Thanks for your interest in our paper! Unfortunately I don't have that preprocessing script. I think it was initially written by Urvashi for the kNN-LM paper (https://github.com/urvashik/knnlm), she might still have it, you could try reaching out to her. 

If you'd like, our hyperparams for the books models (this goes in the `fairseq/models/transformer_lm.py` file) are:
```
@register_model_architecture('transformer_lm', 'transformer_lm_books')
def transformer_lm_books(args):
    args.decoder_layers = getattr(args, 'decoder_layers', 16)
    args.decoder_attention_heads = getattr(args, 'decoder_attention_heads', 8)
    args.dropout = getattr(args, 'dropout', 0.3)
    args.adaptive_input = getattr(args, 'adaptive_input', False)
    args.tie_adaptive_weights = getattr(args, 'tie_adaptive_weights', False)
    args.attention_dropout = getattr(args, 'attention_dropout', 0.1)
    args.activation_dropout = getattr(args, 'activation_dropout', 0.1)
    args.no_decoder_final_norm = getattr(args, 'no_decoder_final_norm', True)
    args.tie_adaptive_proj = getattr(args, 'tie_adaptive_proj', False)
    transformer_lm_big(args)
```

What you could do is just to divide the dataset into train/valid/test splits yourself and then train our model as the baseline and compare to that. 

Happy to answer any other questions you might have.
